[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ping"
path = "src/bin/ping.rs"

[[bin]]
name = "host"
path = "src/bin/host.rs"

[[bin]]
name = "dns"
path = "src/bin/dns.rs"

[[bin]]
name = "tcpclient"
path = "src/bin/tcpclient.rs"

[[bin]]
name = "tcpserver"
path = "src/bin/tcpserver.rs"

[[bin]]
name = "tftp"
path = "src/bin/tftp.rs"

[[bin]]
name = "ntp"
path = "src/bin/ntp.rs"

[[bin]]
name = "whois"
path = "src/bin/whois.rs"

[[bin]]
name = "netstat"
path = "src/bin/netstat.rs"

[[bin]]
name = "http_server"
path = "src/bin/http_server.rs"

[[bin]]
name = "curl"
path = "src/bin/curl.rs"

[[bin]]
name = "ssh_client"
path = "src/bin/ssh_client.rs"

[[bin]]
name = "ssh_server"
path = "src/bin/ssh_server.rs"

[dependencies]
libnet = { path = "../libnet" }
fastrand = "2"
tiny_http = "0.12"
ureq = "2.5"
ssh2 = "0.9"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }